### ISSUE TITLE
Unable to stop docker container with SIGINT

### ISSUE THREAD

**Issue by timofurrer** [randombenj/docat#11]
I cannot stop the docker container from running with Ctrl+C - I think that should always be possible :)

**Comment by fliiiix** [comment]
Its not trivial since we want to start nginx and the flask app in the same container I tried :disappointed:

**Comment by timofurrer** [comment]
Does it have to be the same container?
Just share a volume for static stuff and use nginx as reverse proxy for gunicorn which runs in a separate container ...

**Comment by fliiiix** [comment]
I mean not a big fan of creating more complexity but yeah that is the proper way to solve this issue - so by all means if you want to do that go ahead :+1:
