### ISSUE TITLE
Participation in Hacktoberfest 2021?

### ISSUE THREAD

**Issue by dinakar29** [randombenj/docat#115]
Not an issue, but more of a suggestion - what do you guys think about including this project for [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/)?

Contributors could pitch in with their contributions for open issues and I think this project needs more exposure and adoption. 

Cheers!

**Comment by randombenj** [comment]
Good idea, forgot that its opt in since last year 😅

**Comment by fliiiix** [comment]
![image](https://user-images.githubusercontent.com/1682954/133041781-7fac78ff-41a4-4d91-8f4a-bd1aaa7018b4.png)
repo is still marked to participate but lets go through the issues and make sure the tags are up to date before the Hacktoberfest starts and then close this issue 

@dinakar29 thanks for the reminder :+1:

**Comment by fliiiix** [comment]
checked all the issues and did my best to tag issues and clean up

Happy Hacking everyone :tada: :taco:
