### ISSUE TITLE
Adding latest version should not create a new version

### ISSUE THREAD

**Issue by jsellares** [randombenj/docat#26]
I have uploaded 2 versions:
2.0 and 2.1

Then I used this command to mark 2.1 as latest:
curl -X PUT http://docs.roche.com/api/LabCore%20File%20Handling/2.1/tags/latest

This created a 3rd entry called "latest", which is fine, but in fact "latest" is a duplicated of "2.1".
2.1 version should just be marked as "latest"

![image](https://user-images.githubusercontent.com/49302499/70704188-cd84da80-1cd1-11ea-975d-c4a1bb129504.png)

**Comment by fliiiix** [comment]
Yes this is the intention of this feature. The idea of this is to generate a constant link. Meaning you can point your customers to something like the stable/latest/whatever version and update the content underneath the link.
