### ISSUE TITLE
Add ability to delete docs

### ISSUE THREAD

**Issue by randombenj** [randombenj/docat#49]
Implement something like `DELETE /api/PROJECT/VERSION`

**Comment by bryantfhayes** [comment]
I would definitely use this!

**Comment by randombenj** [comment]
Before we merge this we need to implement some kind of token. 
As discussed with @fliiiix the simplest aproach would be to generate a uuid
when a project is created, which is then returned after creation.
When one wants to delete a version he has to pass this token.
