### ISSUE TITLE
s3 backend

### ISSUE THREAD

**Issue by AndersonReyes** [randombenj/docat#73]
allow serving/proxying docs from s3.

I would like to give this shot or if someone else wants a crack at it we can work together on this.

What do ya think about this feature?

@randombenj @timofurrer @fliiiix

**Comment by randombenj** [comment]
Sounds interesting in deed! What did you have in mind, storing the data in a S3 bucket and then mounting/serving it to the server or hosting the docs on s3 and then just proxy them through a hosted docat instance?

**Comment by AndersonReyes** [comment]
I was thinking first the former. Serving the docs from s3 using the server. Retrieving files on the fly (using signed urls for css etc) at request time (prob with some configurable caching to avoid repeated request). We can also do the latter too

**Comment by randombenj** [comment]
I think the later is not really doable with the current architecture as the docs page basically is loaded in an iframe and we read the url from the iframe to update the permalink in the url (including the project/version).
Could you maybe give me some more infos about why you want to do this? Thinking about this 'proxy' implementation the content could change on the s3 side and then the point of having versioned docs would be a bit obsolete or what do you think?

**Comment by AndersonReyes** [comment]
In our usecase we use k8s to deploy our apps, so storage is ephemeral unless we setup some nfs infrastructure to handle it. We could just seup am ec2 instance but we'll need se. Backup to s3 anyways in case the instance dies and we lost the disk files. Though you are right that versioning would be pretty useless in that context. In our case that's just something we know happens but each team decides how to handle that.

**Comment by randombenj** [comment]
Okay the If I understand right, this could be implemented in two ways (I am not verry familiar with s3 so correct me if I am wrong):

1) Mount the bucket on the system you host docat and then just use it as is (this wouldn't require any changes on docat, and would be quite simple imo)
2) Implement an api on docat where you can post specific 'bucket info' like ACCESS_KEY,  SECRET_KEY and bucket name, and then this project would just proxy files from the bucket (not shure about security here dough :sweat_smile:)

What prevents you from doing 1?

**Comment by AndersonReyes** [comment]
For 1. It depends how you have your server setup, since we use kubernetes it requires more work than a simple s3fs mount, (volumes(nfs) + extra process to auto sync the bucket on some cadance)

**Comment by randombenj** [comment]
Okay for me it would be fine to have something like described in 2. What do you think @fliiiix ?

**Comment by fliiiix** [comment]
Ok I finally got around to think about this. 
I'm not convinced yet that this should be built in docat. 

Nonetheless I see you use-case  but when we implement something like @randombenj recommended.
I think it would be better to build this as a standalone script.

So tldr my recommendation would be to provide a script/tool which sync with s3.
Something which checks s3 for new docs and copies them to the docat instance and the other way around.
This script/tool can potently be part of this repo.


Let me know what you think.

**Comment by fliiiix** [comment]
closing this as it is likely not going to happen - lets reopen it if someone is willing to work on this
