### ISSUE TITLE
Simple upload page doesn't work

### ISSUE THREAD

**Issue by muXxer** [randombenj/docat#76]
Hello!

yesterday I stumbled over this project and this is exactly what I need, very cool!
Everything works fine so far, except the upload page. I'm not sure if I'm doing something wrong.
Tested in different browsers, always the same result.

I use the latest "unstable" docker container "aac8d43c91a2".

Problem description:
In the moment I choose the file to upload in the file selected I get an error in the browser console:
`this.$el.validity is undefined`

If I click upload afterwards, nothing in the browser UI happens except resetting all fields.
The docat server responds with `"No file part in the request"` in the browser console.

Uploading the same file via curl always works fine.

![image](https://user-images.githubusercontent.com/32371094/92885261-e2ce9700-f412-11ea-8e2c-774fe28dbd15.png)

**Comment by randombenj** [comment]
Yes this might be because of the unstable container, could you maybe try with the latest release:

```
docker run \
  --detach \
  --volume /path/to/doc:/var/docat/doc/ \
  --volume /path/to/locations:/etc/nginx/locations.d/ \
  --publish 8000:80 \
  randombenj/docat:0.0.13
```

I think there might be still some unstable things in the unstable container :P

**Comment by randombenj** [comment]
Oh no looks like it's really broken on master
